* My Emacs config specification

The Emacs lisp code in my config shall be divided into two categories:
startup elisp code and Just-In-Time (JIT) elisp code. Startup elisp
code is loaded when Emacs starts, and JIT elisp code only loads when
a file corresponding to a respective mode is opened. The purpose of this
is to reduce load time in Emacs as much as possible.

** Quality of Life
*** Separation Between Installing Packages and Running
When the following command is run,

#+begin_src
  git clone --recurse-submodules <repo-url> ~/.config/emacs
#+end_src

the Emacs repo will be successfully cloned to that location. When
starting up Emacs, either as a process or service, packages should not
start downloading; they should have already been downloaded as a
submodule when git clone was run.

**** Rationale
Any repo where a user has to wait a couple of minutes to load packages
from Melpa or another Emacs package repository is just not up to my
taste personally. When a user downloads a JavaScript project, they
cannot just run ~npm run~; they must run ~npm install~ and then ~npm
run~. I would

***

** General
When the keybinding "C-x g" is pressed, Magit should be invoked.

** Productivity
Projects are composed of ToDos.

There are two kinds of Projects: UnorderedProjects and
OrderedProjects.

Habits are a kind of ToDo, a RepeatingTodo. So Habits can be said to
extend/inherit from a ToDo.

Areas can contain Projects and ToDos.

Resources are their own thing.

#+begin_src ditaa

#+end_src

#+begin_src plantuml
#+end_src

** UI/UX
The menu bar shall be hidden.

The tool bar shall be hidden.

The scroll bar shall be hidden.

Line numbers shall be displayed in all modes, except in any mode that
is a shell (e.g. shell-mode, vterm, eshell, etc.)

** Programming
For programming languages with a REPL, the keypress "C-c C-z" shall
open a REPL in another window if a REPL process was started.

Imported objects/functions that are not used shall be greyed out.

When the point in Emacs is on a function name, the keypress "M-." goes
directly to the function definition.

When the point in Emacs is on a function name, the keypress
"C-c C-d d" shall fetch the documentation for that function.
