;;; loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Commentary:

;; This file will be copied to ldefs-boot.el and checked in
;; periodically.

;;; Code:



;;; Generated autoloads from config/haskell.el

(autoload 'my/haskell-setup "config/haskell")


;;; Generated autoloads from config/java.el

(autoload 'my/java-setup "config/java")


;;; Generated autoloads from config/ocaml.el

(autoload 'my/ocaml-setup "config/ocaml")


;;; Generated autoloads from config/org.el

(autoload 'my/org-setup "config/org")
(autoload 'my/org-agenda-setup "config/org")


;;; Generated autoloads from config/scheme.el

(autoload 'my/scheme-setup "config/scheme")


;;; Generated autoloads from config/python.el

(autoload 'my/python-setup "config/python")

;;; End of scraped data

(provide 'loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; loaddefs.el ends here
