;;; loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Commentary:

;; This file will be copied to ldefs-boot.el and checked in
;; periodically.

;;; Code:



;;; Generated autoloads from config/haskell.el

(autoload 'my/haskell-setup "config/haskell")


;;; Generated autoloads from config/java.el

(autoload 'my/java-setup "config/java")
(register-definition-prefixes "config/java" '("my/get-"))


;;; Generated autoloads from config/ocaml.el

(autoload 'my/ocaml-setup "config/ocaml")


;;; Generated autoloads from config/org.el

(autoload 'my/org-setup "config/org")
(autoload 'my/org-agenda-setup "config/org")
(register-definition-prefixes "config/org" '("my/org-ispell"))


;;; Generated autoloads from config/scheme.el

(autoload 'my/scheme-setup "config/scheme")


;;; Generated autoloads from config/python.el

(autoload 'my/python-setup "config/python")
(register-definition-prefixes "config/python" '("python-compile-command"))


;;; Generated autoloads from config/rust.el

(autoload 'my/rust-setup "config/rust")
(register-definition-prefixes "config/rust" '("my/rustic-mode-hook"))


;;; Generated autoloads from config/common-lisp.el

(autoload 'my/common-lisp-setup "config/common-lisp" "\
")


;;; Generated autoloads from config/racket.el

(autoload 'my/racket-setup "config/racket")


;;; Generated autoloads from config/clojure.el

(autoload 'my/clojure-setup "config/clojure")


;;; Generated autoloads from config/typescript.el

(autoload 'my/typescript-setup "config/typescript")


;;; Generated autoloads from config/docker.el

(autoload 'my/docker-setup "config/docker")


;;; Generated autoloads from config/latex.el

(autoload 'my/latex-setup "config/latex")
(register-definition-prefixes "config/latex" '("my/LaTeX-self-insert"))


;;; Generated autoloads from config/perl.el

(autoload 'my/perl-setup "config/perl")


;;; Generated autoloads from config/c.el

(autoload 'my/c-setup "config/c" "\
Sets up Treesitter for C.")



;;; Generated autoloads from config/eshell.el

(autoload 'my/eshell-setup "config/eshell")

;;; End of scraped data

(provide 'loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; loaddefs.el ends here
